apiVersion: v1
kind: Service
metadata:
  name: {{ include "monocle.api.fullname" . }}
  labels:
    {{- include "monocle.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: "9876"
      port: 9876
      targetPort: 9876
    - name: "9877"
      port: 9877
      targetPort: 9877
  selector:
    {{- include "monocle.api.selectorLabels" . | nindent 4 }}
