apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: crawler-storage
  name: crawler-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
