apiVersion: v1
kind: Service
metadata:
  name: {{ include "monocle.web.fullname" . }}
  labels:
    {{- include "monocle.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    {{- include "monocle.web.selectorLabels" . | nindent 4 }}
